apiVersion: v1
kind: Pod
metadata:
  name: data-capture
  labels:
    app: data-capture
spec:
  initContainers:
  - name: init-networking
    image: dannysievers/init-data-capture
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
  containers:
  - name: diabetes-model
    image: dannysievers/diabetes-progression
    ports:
    - containerPort: 80
  - name: data-capture-sidecar
    image: dannysievers/data-capture-sidecar
    ports:
    - containerPort: 8000